import { useEffect, useMemo, useState } from "react";
import { ArrowLeft, Check, Copy, ExternalLink, LayoutDashboard, MessageCircle, QrCode, Save, Settings2 } from "lucide-react";
import { toast } from "sonner";
import { trpc } from "@/lib/trpc";

const baseUrl = import.meta.env.BASE_URL;
const siteUrl = typeof window !== "undefined" ? `${window.location.origin}${baseUrl}` : baseUrl;

export default function Admin() {
  const [whatsapp, setWhatsapp] = useState("");
  const [tableNumber, setTableNumber] = useState("");
  const [generatedTable, setGeneratedTable] = useState("");
  const settings = trpc.settings.get.useQuery();
  const update = trpc.settings.updateWhatsapp.useMutation({ onSuccess: (data) => { setWhatsapp(data.whatsapp); toast.success("WhatsApp atualizado"); } });

  useEffect(() => { if (settings.data?.whatsapp) setWhatsapp(settings.data.whatsapp); }, [settings.data?.whatsapp]);

  const tableUrl = useMemo(() => generatedTable ? `${siteUrl}?mesa=${encodeURIComponent(generatedTable)}` : "", [generatedTable]);
  const qrUrl = tableUrl ? `https://api.qrserver.com/v1/create-qr-code/?size=280x280&margin=12&data=${encodeURIComponent(tableUrl)}` : "";

  const save = (event: React.FormEvent) => {
    event.preventDefault();
    update.mutate({ whatsapp: whatsapp.replace(/\D/g, "") });
  };
  const generateQr = (event: React.FormEvent) => {
    event.preventDefault();
    const value = tableNumber.replace(/\D/g, "").slice(0, 3);
    if (!value) { toast.error("Digite o número da mesa"); return; }
    setGeneratedTable(value);
  };
  const copyLink = async () => {
    await navigator.clipboard.writeText(tableUrl);
    toast.success("Link da mesa copiado");
  };

  return <div className="min-h-screen bg-[#f6f2ea] text-[#1d201c]">
    <aside className="fixed inset-y-0 left-0 z-40 hidden w-64 flex-col border-r border-[#ded8cc] bg-white lg:flex"><div className="flex items-center gap-3 border-b border-[#eee9df] px-6 py-6"><div className="flex h-11 w-11 items-center justify-center rounded-[14px] bg-[#1d201c] text-xl text-[#e8ff61]">✦</div><div><div className="font-display text-lg font-black tracking-[-0.05em]">BOCA & BRASA</div><div className="mt-1 font-mono text-[9px] uppercase tracking-[0.18em] text-[#8a8f85]">central operacional</div></div></div><nav className="flex-1 space-y-2 px-4 py-6"><a href={`${baseUrl}cozinha`} className="flex items-center gap-3 rounded-xl px-4 py-3 text-sm font-bold text-[#7a8076] transition hover:bg-[#f6f2ea]"><LayoutDashboard size={17} /> Pedidos da cozinha</a><a href={`${baseUrl}admin`} className="flex items-center gap-3 rounded-xl bg-[#e8ff61] px-4 py-3 text-sm font-bold text-[#1d201c]"><Settings2 size={17} /> Configuração</a><a href="#qrcodes" className="flex items-center gap-3 rounded-xl px-4 py-3 text-sm font-bold text-[#7a8076] transition hover:bg-[#f6f2ea]"><QrCode size={17} /> QR Codes por mesa</a></nav><div className="border-t border-[#eee9df] p-4"><a href={baseUrl} className="flex items-center gap-3 rounded-xl px-4 py-3 text-sm font-bold text-[#7a8076] transition hover:bg-[#f6f2ea]"><ExternalLink size={17} /> Abrir cardápio</a></div></aside>
    <div className="lg:pl-64"><header className="border-b border-[#d9d3c7] bg-white/75"><div className="container flex min-h-[78px] items-center justify-between gap-4"><div><div className="font-mono text-[10px] uppercase tracking-[0.2em] text-[#8a8f85]">configuração</div><h1 className="mt-1 font-display text-3xl font-black tracking-[-0.06em]">Central operacional</h1></div><div className="flex items-center gap-2"><a href={`${baseUrl}cozinha`} className="flex h-10 items-center gap-2 rounded-xl border border-[#d9d3c7] px-3 font-display text-xs font-bold"><LayoutDashboard size={14} /> Cozinha</a><a href={baseUrl} className="hidden h-10 items-center gap-2 rounded-xl border border-[#d9d3c7] px-3 font-display text-xs font-bold sm:flex"><ExternalLink size={14} /> Cardápio</a></div></div></header>
      <main className="container max-w-6xl pb-14 pt-8"><a href={`${baseUrl}cozinha`} className="inline-flex items-center gap-2 font-mono text-[10px] uppercase tracking-[0.15em] text-[#7e8479] hover:text-[#1d201c]"><ArrowLeft size={14} /> voltar para a cozinha</a><div className="mt-8 grid gap-5 xl:grid-cols-[1.1fr_0.9fr]"><section className="rounded-[28px] bg-[#1d201c] p-6 text-white sm:p-9"><div className="flex h-12 w-12 items-center justify-center rounded-2xl bg-[#e8ff61] text-[#1d201c]"><MessageCircle size={22} /></div><div className="mt-8 font-mono text-[10px] uppercase tracking-[0.2em] text-[#98a38e]">destino dos pedidos</div><h2 className="mt-2 font-display text-4xl font-black leading-[0.95] tracking-[-0.07em] sm:text-5xl">Receba tudo<br /><span className="text-[#e8ff61]">no WhatsApp.</span></h2><p className="mt-5 max-w-md text-sm leading-6 text-[#bdc5b6]">Cadastre o número que deve receber os pedidos finalizados. O cliente poderá enviar o resumo pelo WhatsApp após a confirmação.</p><form onSubmit={save} className="mt-8"><label htmlFor="whatsapp" className="font-mono text-[10px] uppercase tracking-[0.15em] text-[#98a38e]">WhatsApp com DDI + DDD</label><div className="mt-2 flex flex-col gap-2 sm:flex-row"><div className="flex flex-1 items-center rounded-xl border border-white/15 bg-white/5 px-4"><MessageCircle size={17} className="mr-3 shrink-0 text-[#e8ff61]" /><input id="whatsapp" value={whatsapp} onChange={(event) => setWhatsapp(event.target.value.replace(/\D/g, "").slice(0, 15))} placeholder="Ex.: 5511999999999" inputMode="numeric" className="h-12 w-full bg-transparent font-mono text-sm text-white outline-none placeholder:text-[#788273]" /></div><button disabled={update.isPending || whatsapp.length < 8} className="flex h-12 items-center justify-center gap-2 rounded-xl bg-[#e8ff61] px-5 font-display text-xs font-black uppercase tracking-[0.08em] text-[#1d201c] transition hover:bg-[#d7ee50] disabled:opacity-50">{update.isPending ? "Salvando…" : <><Save size={15} /> Salvar número</>}</button></div><div className="mt-3 flex items-center gap-2 text-[11px] text-[#98a38e]"><Check size={14} className="text-[#e8ff61]" /> Sem número padrão: cadastre o WhatsApp oficial da lanchonete.</div></form></section>
        <section id="qrcodes" className="rounded-[28px] border border-[#ded8cc] bg-white p-6 sm:p-9"><div className="flex h-12 w-12 items-center justify-center rounded-2xl bg-[#e8ff61]"><QrCode size={22} /></div><div className="mt-8 font-mono text-[10px] uppercase tracking-[0.2em] text-[#8a8f85]">identificação por mesa</div><h2 className="mt-2 font-display text-3xl font-black tracking-[-0.06em]">QR Code da mesa</h2><p className="mt-3 text-sm leading-6 text-[#7a8076]">Gere um QR Code para cada mesa. Ao escanear, o cardápio já abre com a mesa identificada.</p><form onSubmit={generateQr} className="mt-6 flex gap-2"><input value={tableNumber} onChange={(event) => setTableNumber(event.target.value.replace(/\D/g, "").slice(0, 3))} placeholder="Mesa 1" inputMode="numeric" className="h-12 min-w-0 flex-1 rounded-xl border border-[#d9d3c7] bg-[#f6f2ea] px-4 font-display font-bold outline-none focus:border-[#1d201c]" aria-label="Número da mesa para QR Code" /><button className="flex h-12 items-center gap-2 rounded-xl bg-[#1d201c] px-4 font-display text-xs font-black uppercase text-white"><QrCode size={16} /> Gerar</button></form>{generatedTable ? <div className="mt-6 rounded-2xl bg-[#f6f2ea] p-5 text-center"><img src={qrUrl} alt={`QR Code da mesa ${generatedTable}`} className="mx-auto h-52 w-52 rounded-xl bg-white p-2" /><div className="mt-4 font-display text-lg font-black">Mesa {generatedTable}</div><p className="mt-1 break-all text-xs text-[#7a8076]">{tableUrl}</p><div className="mt-4 flex justify-center gap-2"><button onClick={copyLink} className="flex items-center gap-2 rounded-xl border border-[#d9d3c7] bg-white px-3 py-2 text-xs font-bold"><Copy size={14} /> Copiar link</button><a href={qrUrl} download={`mesa-${generatedTable}.png`} target="_blank" rel="noreferrer" className="flex items-center gap-2 rounded-xl bg-[#e8ff61] px-3 py-2 text-xs font-bold"><ExternalLink size={14} /> Abrir QR</a></div></div> : <div className="mt-6 rounded-2xl border border-dashed border-[#d9d3c7] p-8 text-center text-sm text-[#8a8f85]">Digite o número da mesa para gerar o QR Code.</div>}</section></div><div className="mt-5 rounded-2xl border border-[#ded8cc] bg-white p-5 text-sm leading-6 text-[#7a8076]"><strong className="text-[#1d201c]">Como funciona:</strong> a mesa escaneia o QR Code, o cliente escolhe os produtos, o pedido chega na cozinha com o número da mesa e o status aparece no acompanhamento do cliente.</div></main>
    </div>
  </div>;
}
